export const STAGES = [
  {
    id: 1,
    name: { de: "Stufe 1", en: "Stage 1" },
    target: {
      power: true,
      phase: false,
      freq: 34,
      fine: -8,
      gain: 42,
      colorR: 0,
      colorG: 0,
      colorB: 0,
      routes: [],
    },
    tolerance: { freq: 16, fine: 18, gain: 18, colorR: 255, colorG: 255, colorB: 255 },
    message: {
      de: "ARCHIV-SIGNAL ERKANNT, SCHLÜSSELRAHMEN INSTABIL. TELEMETRIE ZEIGT: FEHLER SIND FRÜH SICHTBAR, WERDEN ABER OFT IGNORIERT. WEISHEIT: WAS DU NICHT MISST, KANNST DU NICHT VERBESSERN.",
      en: "ARCHIVE SIGNAL DETECTED, KEY FRAME UNSTABLE. TELEMETRY SHOWS THIS: FAILURES APPEAR EARLY BUT ARE OFTEN IGNORED. WISDOM: WHAT YOU DO NOT MEASURE, YOU CANNOT IMPROVE.",
    },
    briefing: {
      de: "Stufe 1: Grundkalibrierung. Farbcode und Patchfeld sind deaktiviert. Konzentriere dich auf Strom, Phase und die drei Regler, um Stabilität aufzubauen.",
      en: "Stage 1: Basic calibration. Color Code and patch panel are disabled. Focus on power, phase, and the three knobs to build signal stability.",
    },
    codeword: { de: "TELEMETRIE", en: "TELEMETRY" },
  },
  {
    id: 2,
    name: { de: "Stufe 2", en: "Stage 2" },
    target: {
      power: true,
      phase: true,
      freq: 59,
      fine: 13,
      gain: 67,
      colorR: 64,
      colorG: 176,
      colorB: 96,
      routes: [],
    },
    tolerance: { freq: 13, fine: 14, gain: 14, colorR: 72, colorG: 72, colorB: 72 },
    message: {
      de: "PRIMZAHLCLUSTER PASSEN, RESONANZFILTER ONLINE. DIE PIPELINE BLEIBT STABIL, WENN SCHNITTSTELLEN KLAR UND KOPPLUNG NIEDRIG BLEIBT. WEISHEIT: EINFACHE GRENZEN RETTEN KOMPLEXE SYSTEME.",
      en: "PRIME CLUSTERS ALIGN, RESONANCE FILTER ONLINE. THE PIPELINE STAYS STABLE WHEN INTERFACES ARE CLEAR AND COUPLING REMAINS LOW. WISDOM: SIMPLE BOUNDARIES SAVE COMPLEX SYSTEMS.",
    },
    briefing: {
      de: "Stufe 2: Feinjustierung mit dem Farbcode. Das Patchfeld bleibt gesperrt. Nutze die drei Farbkanäle, um die Trägerspur präzise auszubalancieren.",
      en: "Stage 2: Fine calibration with the Color Code. The patch panel remains locked. Use the three color channels to balance the carrier precisely.",
    },
    codeword: { de: "PIPELINE", en: "PIPELINE" },
  },
  {
    id: 3,
    name: { de: "Stufe 3", en: "Stage 3" },
    target: {
      power: true,
      phase: true,
      freq: 72,
      fine: -19,
      gain: 58,
      colorR: 196,
      colorG: 96,
      colorB: 40,
      routes: ["PRE->FLT"],
    },
    tolerance: { freq: 10, fine: 11, gain: 11, colorR: 52, colorG: 52, colorB: 52 },
    message: {
      de: "RÜCKKOPPLUNG ERKANNT, INFRASTRUKTUR-KOMPATIBILITÄT STEIGT. REPLIKATION GLÄTTET LASTSPITZEN UND VERKÜRZT WIEDERHERSTELLUNG. WEISHEIT: REDUNDANZ IST KEIN LUXUS, SONDERN BETRIEBSSICHERHEIT.",
      en: "FEEDBACK DETECTED, INFRASTRUCTURE COMPATIBILITY RISING. REPLICATION SMOOTHS TRAFFIC SPIKES AND SHORTENS RECOVERY. WISDOM: REDUNDANCY IS NOT LUXURY, IT IS OPERATIONAL SAFETY.",
    },
    briefing: {
      de: "Stufe 3: Verkabelung freigeschaltet, aber auf ein Kabel begrenzt. Wähle den Pfad mit Bedacht und kombiniere ihn mit einem gezielten Farbcode.",
      en: "Stage 3: Patching unlocked, but limited to one cable. Choose that route carefully and combine it with a focused color code.",
    },
    codeword: { de: "REPLIKATION", en: "REPLICATION" },
  },
  {
    id: 4,
    name: { de: "Stufe 4", en: "Stage 4" },
    target: {
      power: true,
      phase: false,
      freq: 16,
      fine: 24,
      gain: 76,
      colorR: 32,
      colorG: 156,
      colorB: 224,
      routes: ["ANT->FLT", "FLT->DEC"],
    },
    tolerance: { freq: 9, fine: 9, gain: 10, colorR: 38, colorG: 38, colorB: 38 },
    message: {
      de: "AUTONOME SYNCHRONISATION BEGINNT, NACHRICHT FAST KLAR. VERSCHLÜSSELUNG SCHÜTZT VERTRAUEN, ABER SCHLÜSSELHYGIENE SCHÜTZT DIE REALITÄT. WEISHEIT: SICHERHEIT IST EIN PROZESS, KEIN SCHALTER.",
      en: "AUTONOMOUS SYNCHRONIZATION STARTS, MESSAGE NEARLY CLEAR. ENCRYPTION PROTECTS TRUST, BUT KEY HYGIENE PROTECTS REALITY. WISDOM: SECURITY IS A PROCESS, NOT A SWITCH.",
    },
    briefing: {
      de: "Stufe 4: Volle Kontrolle aktiv. Farbcode und Patchfeld sind komplett freigegeben. Nutze mehrere Kabel und eine saubere Farb-Balance für gezielte Signatur-Formung.",
      en: "Stage 4: Full control unlocked. Color Code and patch panel are fully available. Use multiple cables and clean color balance for targeted signature shaping.",
    },
    codeword: { de: "VERSCHLÜSSELUNG", en: "ENCRYPTION" },
  },
  {
    id: 5,
    name: { de: "Stufe 5", en: "Stage 5" },
    target: {
      power: true,
      phase: true,
      freq: 47,
      fine: 3,
      gain: 51,
      colorR: 224,
      colorG: 48,
      colorB: 168,
      routes: ["ANT->PRE", "PRE->FLT", "FLT->DEC", "DEC->ANT"],
    },
    tolerance: { freq: 7, fine: 7, gain: 8, colorR: 26, colorG: 26, colorB: 26 },
    message: {
      de: "HANDSHAKE BESTANDEN, PHASE ZWEI INITIIERT. AUTOMATISIERUNG ERHÖHT TEMPO, DOCH VERANTWORTUNG MUSS IM DESIGN VERANKERT BLEIBEN. WEISHEIT: SKALIERUNG OHNE ETHIK VERVIELFACHT FEHLER.",
      en: "HANDSHAKE ACCEPTED, PHASE TWO INITIATED. AUTOMATION INCREASES SPEED, YET RESPONSIBILITY MUST STAY EMBEDDED IN DESIGN. WISDOM: SCALING WITHOUT ETHICS MULTIPLIES MISTAKES.",
    },
    briefing: {
      de: "Stufe 5: Endphase. Alle Werkzeuge sind aktiv und die Toleranzen sind eng. Jeder Regler, jedes Kabel und jeder RGB-Kanal beeinflusst den finalen Lock deutlich.",
      en: "Stage 5: Final phase. All tools are active and tolerances are tight. Every control, cable, and RGB channel strongly affects the final lock.",
    },
    codeword: { de: "AUTOMATISIERUNG", en: "AUTOMATION" },
  },
];
